#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#from:http://projecteuler.net/problem=2

num=1
pnum=0
pnumbuf=0
numsum=0
while num+pnum<4000000:
	pnumbuf=num
	num+=pnum
	pnum=pnumbuf
	if num%2==0:
		numsum+=num
print numsum