#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#Let us list the factors of the first seven triangle numbers:
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
#10: 1,2,5,10
#15: 1,3,5,15
#21: 1,3,7,21
#28: 1,2,4,7,14,28
#We can see that 28 is the first triangle number to have over five divisors.
#What is the value of the first triangle number to have over five hundred divisors?
#from:http://projecteuler.net/problem=12

num=0
numlist=[]
for i in range(1,50000):#upper range needs to be 1 more than the intended as need to start at 1 instead of 0
	num+=i
	numlist[:]=[]
	for j in range(1,num+1):
		if num%j==0:
			numlist.append(j)
	if len(numlist)>500:
		print num
		print len(numlist)
		print i
		print numlist
		exit(0)